matrix:
  include:
    - language: java
      script:
        - (cd tau1-junit ; mvn test)
    - language: java
      script:
        - (cd tau3-bdd ; mvn test)
    - language: java
      script:
        - (cd tau3-bdd-jbehave ; mvn integration-test)
    - language: java
      script:
        - (cd tau6-robot-cli/app ; mvn package ; cd ../test ; mvn robotframework:run)
